name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ckan-version: ['2.9', '2.10']
        include:
          - ckan-version: '2.9'
            ckan-image: ckan/ckan-base:2.9.11
            solr-image: ckan/ckan-solr:2.9-solr8
            postgres-image: ckan/ckan-postgres-dev:2.9
          - ckan-version: '2.10'
            ckan-image: ckan/ckan-base:2.10
            solr-image: ckan/ckan-solr:2.10-solr8
            postgres-image: ckan/ckan-postgres-dev:2.10

    container:
      image: ${{ matrix.ckan-image }}

    services:
      solr:
        image: ${{ matrix.solr-image }}
      postgres:
        image: ${{ matrix.postgres-image }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:3

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      # Install any extra requirements your extension has here (dev requirements, other extensions etc)
      run: |
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        pip install -e .

    - name: Set Git safe directory
      run: git config --global --add safe.directory /__w/ckanext-short-urls/ckanext-short-urls

    - name: Checkout custom branch for CKAN 2.9
      if: matrix.ckan-version == '2.9'
      run: |
        git fetch origin
        git checkout dev-2.9

    - name: Setup extension
      # Extra initialization steps
      run: |
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

        ckan -c test.ini db init
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.short_urls --disable-warnings ckanext/short_urls
